name: Python Package Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine  # Install necessary packages

      - name: Install local package
        run: pip install .


      - name: Run Lint
        run: make lint

      - name: Extract version from __version__.py
        id: get_version
        run: echo "::set-output name=VERSION::$(python -c "import parcllabs; print(parcllabs.__version__)")"

      - name: Tag Repository
        uses: actions/github-script@v5
        with:
          script: |
            const tagName = '${{ steps.get_version.outputs.VERSION }}';
            const ref = 'refs/tags/' + tagName;
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: ref,
              sha: context.sha
            });

      - name: Build Package
        run: |
          python setup.py clean --all sdist bdist_wheel --universal

      - name: Check package
        run: |
          python -m twine check dist/*

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_KEY }}
        run: |
          twine upload --repository testpypi dist/*
