# ruff.toml
line-length = 88
indent-width = 4

target-version = "py311"

[lint]
select = ["E", "F", "B", "I", "W", "C", "B", "UP", "N", "ANN", "S", "A", "COM", "DTZ", "T10", "RET", "SLF", "ARG", "PD", "PL", "RUF", "PTH", "PLR", "TRY"]
ignore = ["COM812", "S101", "PLR0913", "TRY003", "SLF001", "PLR2004"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"