name: Parcl Labs Python Package Release Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pip and Tools
        run: |
          python -m pip install --upgrade pip
          pip install pipenv twine build

      - name: Install dependencies
        run: |
          PIPENV_PYTHON=$(which python)
          pipenv install --dev --python "$PIPENV_PYTHON"

      - name: Run tests
        run: |
          pipenv run make test  # Use makefile to run tests (assumes 'make test' is setup to run pytest)

      - name: Run Lint
        run: |
          pipenv run make lint  # Use makefile to run lint (assumes 'make lint' is setup)